/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConsumerRouteImport } from './routes/consumer'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as ConsumerIndexRouteImport } from './routes/consumer.index'
import { Route as ConsumerComplaintsRouteImport } from './routes/consumer.complaints'
import { Route as ConsumerRightsRouteImport } from './routes/consumer.rights'
import { Route as InspectorIndexRouteImport } from './routes/inspector.index'
import { Route as InspectorInspectionsRouteImport } from './routes/inspector.inspections'
import { Route as InspectorProfileRouteImport } from './routes/inspector.profile'
import { Route as InspectorReportsRouteImport } from './routes/inspector.reports'
import { Route as InspectorScanRouteImport } from './routes/inspector.scan'
import { Route as InspectorInspectionsIndexRouteImport } from './routes/inspector.inspections.index'
import { Route as InspectorInspectionsIdRouteImport } from './routes/inspector.inspections.$id'
import { Route as InspectorReportsIndexRouteImport } from './routes/inspector.reports.index'
import { Route as InspectorReportsIdRouteImport } from './routes/inspector.reports.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerRoute = ConsumerRouteImport.update({
  id: '/consumer',
  path: '/consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerIndexRoute = ConsumerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsumerRoute,
} as any)
const ConsumerComplaintsRoute = ConsumerComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => ConsumerRoute,
} as any)
const ConsumerRightsRoute = ConsumerRightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => ConsumerRoute,
} as any)
const InspectorIndexRoute = InspectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorInspectionsRoute = InspectorInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorProfileRoute = InspectorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorReportsRoute = InspectorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorScanRoute = InspectorScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorInspectionsIndexRoute =
  InspectorInspectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InspectorInspectionsRoute,
  } as any)
const InspectorInspectionsIdRoute = InspectorInspectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InspectorInspectionsRoute,
} as any)
const InspectorReportsIndexRoute = InspectorReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InspectorReportsRoute,
} as any)
const InspectorReportsIdRoute = InspectorReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InspectorReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consumer': typeof ConsumerRouteWithChildren
  '/inspector': typeof InspectorRouteWithChildren
  '/consumer/complaints': typeof ConsumerComplaintsRoute
  '/consumer/rights': typeof ConsumerRightsRoute
  '/inspector/inspections': typeof InspectorInspectionsRouteWithChildren
  '/inspector/profile': typeof InspectorProfileRoute
  '/inspector/reports': typeof InspectorReportsRouteWithChildren
  '/inspector/scan': typeof InspectorScanRoute
  '/consumer/': typeof ConsumerIndexRoute
  '/inspector/': typeof InspectorIndexRoute
  '/inspector/inspections/$id': typeof InspectorInspectionsIdRoute
  '/inspector/reports/$id': typeof InspectorReportsIdRoute
  '/inspector/inspections/': typeof InspectorInspectionsIndexRoute
  '/inspector/reports/': typeof InspectorReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consumer/complaints': typeof ConsumerComplaintsRoute
  '/consumer/rights': typeof ConsumerRightsRoute
  '/inspector/profile': typeof InspectorProfileRoute
  '/inspector/scan': typeof InspectorScanRoute
  '/consumer': typeof ConsumerIndexRoute
  '/inspector': typeof InspectorIndexRoute
  '/inspector/inspections/$id': typeof InspectorInspectionsIdRoute
  '/inspector/reports/$id': typeof InspectorReportsIdRoute
  '/inspector/inspections': typeof InspectorInspectionsIndexRoute
  '/inspector/reports': typeof InspectorReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consumer': typeof ConsumerRouteWithChildren
  '/inspector': typeof InspectorRouteWithChildren
  '/consumer/complaints': typeof ConsumerComplaintsRoute
  '/consumer/rights': typeof ConsumerRightsRoute
  '/inspector/inspections': typeof InspectorInspectionsRouteWithChildren
  '/inspector/profile': typeof InspectorProfileRoute
  '/inspector/reports': typeof InspectorReportsRouteWithChildren
  '/inspector/scan': typeof InspectorScanRoute
  '/consumer/': typeof ConsumerIndexRoute
  '/inspector/': typeof InspectorIndexRoute
  '/inspector/inspections/$id': typeof InspectorInspectionsIdRoute
  '/inspector/reports/$id': typeof InspectorReportsIdRoute
  '/inspector/inspections/': typeof InspectorInspectionsIndexRoute
  '/inspector/reports/': typeof InspectorReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/consumer'
    | '/inspector'
    | '/consumer/complaints'
    | '/consumer/rights'
    | '/inspector/inspections'
    | '/inspector/profile'
    | '/inspector/reports'
    | '/inspector/scan'
    | '/consumer/'
    | '/inspector/'
    | '/inspector/inspections/$id'
    | '/inspector/reports/$id'
    | '/inspector/inspections/'
    | '/inspector/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/consumer/complaints'
    | '/consumer/rights'
    | '/inspector/profile'
    | '/inspector/scan'
    | '/consumer'
    | '/inspector'
    | '/inspector/inspections/$id'
    | '/inspector/reports/$id'
    | '/inspector/inspections'
    | '/inspector/reports'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/consumer'
    | '/inspector'
    | '/consumer/complaints'
    | '/consumer/rights'
    | '/inspector/inspections'
    | '/inspector/profile'
    | '/inspector/reports'
    | '/inspector/scan'
    | '/consumer/'
    | '/inspector/'
    | '/inspector/inspections/$id'
    | '/inspector/reports/$id'
    | '/inspector/inspections/'
    | '/inspector/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConsumerRoute: typeof ConsumerRouteWithChildren
  InspectorRoute: typeof InspectorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer': {
      id: '/consumer'
      path: '/consumer'
      fullPath: '/consumer'
      preLoaderRoute: typeof ConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer/': {
      id: '/consumer/'
      path: '/'
      fullPath: '/consumer/'
      preLoaderRoute: typeof ConsumerIndexRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/consumer/complaints': {
      id: '/consumer/complaints'
      path: '/complaints'
      fullPath: '/consumer/complaints'
      preLoaderRoute: typeof ConsumerComplaintsRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/consumer/rights': {
      id: '/consumer/rights'
      path: '/rights'
      fullPath: '/consumer/rights'
      preLoaderRoute: typeof ConsumerRightsRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/inspector/': {
      id: '/inspector/'
      path: '/'
      fullPath: '/inspector/'
      preLoaderRoute: typeof InspectorIndexRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/inspections': {
      id: '/inspector/inspections'
      path: '/inspections'
      fullPath: '/inspector/inspections'
      preLoaderRoute: typeof InspectorInspectionsRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/profile': {
      id: '/inspector/profile'
      path: '/profile'
      fullPath: '/inspector/profile'
      preLoaderRoute: typeof InspectorProfileRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/reports': {
      id: '/inspector/reports'
      path: '/reports'
      fullPath: '/inspector/reports'
      preLoaderRoute: typeof InspectorReportsRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/scan': {
      id: '/inspector/scan'
      path: '/scan'
      fullPath: '/inspector/scan'
      preLoaderRoute: typeof InspectorScanRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/inspections/': {
      id: '/inspector/inspections/'
      path: '/'
      fullPath: '/inspector/inspections/'
      preLoaderRoute: typeof InspectorInspectionsIndexRouteImport
      parentRoute: typeof InspectorInspectionsRoute
    }
    '/inspector/inspections/$id': {
      id: '/inspector/inspections/$id'
      path: '/$id'
      fullPath: '/inspector/inspections/$id'
      preLoaderRoute: typeof InspectorInspectionsIdRouteImport
      parentRoute: typeof InspectorInspectionsRoute
    }
    '/inspector/reports/': {
      id: '/inspector/reports/'
      path: '/'
      fullPath: '/inspector/reports/'
      preLoaderRoute: typeof InspectorReportsIndexRouteImport
      parentRoute: typeof InspectorReportsRoute
    }
    '/inspector/reports/$id': {
      id: '/inspector/reports/$id'
      path: '/$id'
      fullPath: '/inspector/reports/$id'
      preLoaderRoute: typeof InspectorReportsIdRouteImport
      parentRoute: typeof InspectorReportsRoute
    }
  }
}

interface ConsumerRouteChildren {
  ConsumerComplaintsRoute: typeof ConsumerComplaintsRoute
  ConsumerRightsRoute: typeof ConsumerRightsRoute
  ConsumerIndexRoute: typeof ConsumerIndexRoute
}

const ConsumerRouteChildren: ConsumerRouteChildren = {
  ConsumerComplaintsRoute: ConsumerComplaintsRoute,
  ConsumerRightsRoute: ConsumerRightsRoute,
  ConsumerIndexRoute: ConsumerIndexRoute,
}

const ConsumerRouteWithChildren = ConsumerRoute._addFileChildren(
  ConsumerRouteChildren,
)

interface InspectorInspectionsRouteChildren {
  InspectorInspectionsIdRoute: typeof InspectorInspectionsIdRoute
  InspectorInspectionsIndexRoute: typeof InspectorInspectionsIndexRoute
}

const InspectorInspectionsRouteChildren: InspectorInspectionsRouteChildren = {
  InspectorInspectionsIdRoute: InspectorInspectionsIdRoute,
  InspectorInspectionsIndexRoute: InspectorInspectionsIndexRoute,
}

const InspectorInspectionsRouteWithChildren =
  InspectorInspectionsRoute._addFileChildren(InspectorInspectionsRouteChildren)

interface InspectorReportsRouteChildren {
  InspectorReportsIdRoute: typeof InspectorReportsIdRoute
  InspectorReportsIndexRoute: typeof InspectorReportsIndexRoute
}

const InspectorReportsRouteChildren: InspectorReportsRouteChildren = {
  InspectorReportsIdRoute: InspectorReportsIdRoute,
  InspectorReportsIndexRoute: InspectorReportsIndexRoute,
}

const InspectorReportsRouteWithChildren =
  InspectorReportsRoute._addFileChildren(InspectorReportsRouteChildren)

interface InspectorRouteChildren {
  InspectorInspectionsRoute: typeof InspectorInspectionsRouteWithChildren
  InspectorProfileRoute: typeof InspectorProfileRoute
  InspectorReportsRoute: typeof InspectorReportsRouteWithChildren
  InspectorScanRoute: typeof InspectorScanRoute
  InspectorIndexRoute: typeof InspectorIndexRoute
}

const InspectorRouteChildren: InspectorRouteChildren = {
  InspectorInspectionsRoute: InspectorInspectionsRouteWithChildren,
  InspectorProfileRoute: InspectorProfileRoute,
  InspectorReportsRoute: InspectorReportsRouteWithChildren,
  InspectorScanRoute: InspectorScanRoute,
  InspectorIndexRoute: InspectorIndexRoute,
}

const InspectorRouteWithChildren = InspectorRoute._addFileChildren(
  InspectorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConsumerRoute: ConsumerRouteWithChildren,
  InspectorRoute: InspectorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
