/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConsumerRouteImport } from './routes/consumer'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminInspectionsRouteImport } from './routes/admin.inspections'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminRulesRouteImport } from './routes/admin.rules'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ConsumerIndexRouteImport } from './routes/consumer.index'
import { Route as ConsumerAccountRouteImport } from './routes/consumer.account'
import { Route as ConsumerChecksRouteImport } from './routes/consumer.checks'
import { Route as ConsumerComplaintsRouteImport } from './routes/consumer.complaints'
import { Route as ConsumerRightsRouteImport } from './routes/consumer.rights'
import { Route as InspectorIndexRouteImport } from './routes/inspector.index'
import { Route as InspectorInspectionsRouteImport } from './routes/inspector.inspections'
import { Route as InspectorProfileRouteImport } from './routes/inspector.profile'
import { Route as InspectorReportsRouteImport } from './routes/inspector.reports'
import { Route as InspectorScanRouteImport } from './routes/inspector.scan'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as OfficerReportsRouteImport } from './routes/officer.reports'
import { Route as OfficerReviewRouteImport } from './routes/officer.review'
import { Route as OfficerSellersRouteImport } from './routes/officer.sellers'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersStaffRouteImport } from './routes/admin.users.staff'
import { Route as ConsumerCheckIdRouteImport } from './routes/consumer.check.$id'
import { Route as InspectorInspectionsIndexRouteImport } from './routes/inspector.inspections.index'
import { Route as InspectorInspectionsIdRouteImport } from './routes/inspector.inspections.$id'
import { Route as InspectorReportsIndexRouteImport } from './routes/inspector.reports.index'
import { Route as InspectorReportsIdRouteImport } from './routes/inspector.reports.$id'
import { Route as OfficerCasesIdRouteImport } from './routes/officer.cases.$id'
import { Route as AdminUsersCustomersIndexRouteImport } from './routes/admin.users.customers.index'
import { Route as AdminUsersCustomersIdRouteImport } from './routes/admin.users.customers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerRoute = ConsumerRouteImport.update({
  id: '/consumer',
  path: '/consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInspectionsRoute = AdminInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ConsumerIndexRoute = ConsumerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsumerRoute,
} as any)
const ConsumerAccountRoute = ConsumerAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ConsumerRoute,
} as any)
const ConsumerChecksRoute = ConsumerChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => ConsumerRoute,
} as any)
const ConsumerComplaintsRoute = ConsumerComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => ConsumerRoute,
} as any)
const ConsumerRightsRoute = ConsumerRightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => ConsumerRoute,
} as any)
const InspectorIndexRoute = InspectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorInspectionsRoute = InspectorInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorProfileRoute = InspectorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorReportsRoute = InspectorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorScanRoute = InspectorScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => InspectorRoute,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerReportsRoute = OfficerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerReviewRoute = OfficerReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerSellersRoute = OfficerSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => OfficerRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersStaffRoute = AdminUsersStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminUsersRoute,
} as any)
const ConsumerCheckIdRoute = ConsumerCheckIdRouteImport.update({
  id: '/check/$id',
  path: '/check/$id',
  getParentRoute: () => ConsumerRoute,
} as any)
const InspectorInspectionsIndexRoute =
  InspectorInspectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InspectorInspectionsRoute,
  } as any)
const InspectorInspectionsIdRoute = InspectorInspectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InspectorInspectionsRoute,
} as any)
const InspectorReportsIndexRoute = InspectorReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InspectorReportsRoute,
} as any)
const InspectorReportsIdRoute = InspectorReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InspectorReportsRoute,
} as any)
const OfficerCasesIdRoute = OfficerCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => OfficerRoute,
} as any)
const AdminUsersCustomersIndexRoute =
  AdminUsersCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AdminUsersRoute,
  } as any)
const AdminUsersCustomersIdRoute = AdminUsersCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/consumer': typeof ConsumerRouteWithChildren
  '/inspector': typeof InspectorRouteWithChildren
  '/officer': typeof OfficerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/consumer/account': typeof ConsumerAccountRoute
  '/consumer/checks': typeof ConsumerChecksRoute
  '/consumer/complaints': typeof ConsumerComplaintsRoute
  '/consumer/rights': typeof ConsumerRightsRoute
  '/inspector/inspections': typeof InspectorInspectionsRouteWithChildren
  '/inspector/profile': typeof InspectorProfileRoute
  '/inspector/reports': typeof InspectorReportsRouteWithChildren
  '/inspector/scan': typeof InspectorScanRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/review': typeof OfficerReviewRoute
  '/officer/sellers': typeof OfficerSellersRoute
  '/admin/': typeof AdminIndexRoute
  '/consumer/': typeof ConsumerIndexRoute
  '/inspector/': typeof InspectorIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/admin/users/staff': typeof AdminUsersStaffRoute
  '/consumer/check/$id': typeof ConsumerCheckIdRoute
  '/inspector/inspections/$id': typeof InspectorInspectionsIdRoute
  '/inspector/reports/$id': typeof InspectorReportsIdRoute
  '/officer/cases/$id': typeof OfficerCasesIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/inspector/inspections/': typeof InspectorInspectionsIndexRoute
  '/inspector/reports/': typeof InspectorReportsIndexRoute
  '/admin/users/customers/$id': typeof AdminUsersCustomersIdRoute
  '/admin/users/customers/': typeof AdminUsersCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/consumer/account': typeof ConsumerAccountRoute
  '/consumer/checks': typeof ConsumerChecksRoute
  '/consumer/complaints': typeof ConsumerComplaintsRoute
  '/consumer/rights': typeof ConsumerRightsRoute
  '/inspector/profile': typeof InspectorProfileRoute
  '/inspector/scan': typeof InspectorScanRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/review': typeof OfficerReviewRoute
  '/officer/sellers': typeof OfficerSellersRoute
  '/admin': typeof AdminIndexRoute
  '/consumer': typeof ConsumerIndexRoute
  '/inspector': typeof InspectorIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/admin/users/staff': typeof AdminUsersStaffRoute
  '/consumer/check/$id': typeof ConsumerCheckIdRoute
  '/inspector/inspections/$id': typeof InspectorInspectionsIdRoute
  '/inspector/reports/$id': typeof InspectorReportsIdRoute
  '/officer/cases/$id': typeof OfficerCasesIdRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/inspector/inspections': typeof InspectorInspectionsIndexRoute
  '/inspector/reports': typeof InspectorReportsIndexRoute
  '/admin/users/customers/$id': typeof AdminUsersCustomersIdRoute
  '/admin/users/customers': typeof AdminUsersCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/consumer': typeof ConsumerRouteWithChildren
  '/inspector': typeof InspectorRouteWithChildren
  '/officer': typeof OfficerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/consumer/account': typeof ConsumerAccountRoute
  '/consumer/checks': typeof ConsumerChecksRoute
  '/consumer/complaints': typeof ConsumerComplaintsRoute
  '/consumer/rights': typeof ConsumerRightsRoute
  '/inspector/inspections': typeof InspectorInspectionsRouteWithChildren
  '/inspector/profile': typeof InspectorProfileRoute
  '/inspector/reports': typeof InspectorReportsRouteWithChildren
  '/inspector/scan': typeof InspectorScanRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/review': typeof OfficerReviewRoute
  '/officer/sellers': typeof OfficerSellersRoute
  '/admin/': typeof AdminIndexRoute
  '/consumer/': typeof ConsumerIndexRoute
  '/inspector/': typeof InspectorIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/admin/users/staff': typeof AdminUsersStaffRoute
  '/consumer/check/$id': typeof ConsumerCheckIdRoute
  '/inspector/inspections/$id': typeof InspectorInspectionsIdRoute
  '/inspector/reports/$id': typeof InspectorReportsIdRoute
  '/officer/cases/$id': typeof OfficerCasesIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/inspector/inspections/': typeof InspectorInspectionsIndexRoute
  '/inspector/reports/': typeof InspectorReportsIndexRoute
  '/admin/users/customers/$id': typeof AdminUsersCustomersIdRoute
  '/admin/users/customers/': typeof AdminUsersCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/consumer'
    | '/inspector'
    | '/officer'
    | '/reset-password'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/inspections'
    | '/admin/notifications'
    | '/admin/rules'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/users'
    | '/consumer/account'
    | '/consumer/checks'
    | '/consumer/complaints'
    | '/consumer/rights'
    | '/inspector/inspections'
    | '/inspector/profile'
    | '/inspector/reports'
    | '/inspector/scan'
    | '/officer/reports'
    | '/officer/review'
    | '/officer/sellers'
    | '/admin/'
    | '/consumer/'
    | '/inspector/'
    | '/officer/'
    | '/admin/users/staff'
    | '/consumer/check/$id'
    | '/inspector/inspections/$id'
    | '/inspector/reports/$id'
    | '/officer/cases/$id'
    | '/admin/users/'
    | '/inspector/inspections/'
    | '/inspector/reports/'
    | '/admin/users/customers/$id'
    | '/admin/users/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/inspections'
    | '/admin/notifications'
    | '/admin/rules'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/sources'
    | '/consumer/account'
    | '/consumer/checks'
    | '/consumer/complaints'
    | '/consumer/rights'
    | '/inspector/profile'
    | '/inspector/scan'
    | '/officer/reports'
    | '/officer/review'
    | '/officer/sellers'
    | '/admin'
    | '/consumer'
    | '/inspector'
    | '/officer'
    | '/admin/users/staff'
    | '/consumer/check/$id'
    | '/inspector/inspections/$id'
    | '/inspector/reports/$id'
    | '/officer/cases/$id'
    | '/admin/users'
    | '/inspector/inspections'
    | '/inspector/reports'
    | '/admin/users/customers/$id'
    | '/admin/users/customers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/consumer'
    | '/inspector'
    | '/officer'
    | '/reset-password'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/inspections'
    | '/admin/notifications'
    | '/admin/rules'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/users'
    | '/consumer/account'
    | '/consumer/checks'
    | '/consumer/complaints'
    | '/consumer/rights'
    | '/inspector/inspections'
    | '/inspector/profile'
    | '/inspector/reports'
    | '/inspector/scan'
    | '/officer/reports'
    | '/officer/review'
    | '/officer/sellers'
    | '/admin/'
    | '/consumer/'
    | '/inspector/'
    | '/officer/'
    | '/admin/users/staff'
    | '/consumer/check/$id'
    | '/inspector/inspections/$id'
    | '/inspector/reports/$id'
    | '/officer/cases/$id'
    | '/admin/users/'
    | '/inspector/inspections/'
    | '/inspector/reports/'
    | '/admin/users/customers/$id'
    | '/admin/users/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConsumerRoute: typeof ConsumerRouteWithChildren
  InspectorRoute: typeof InspectorRouteWithChildren
  OfficerRoute: typeof OfficerRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer': {
      id: '/consumer'
      path: '/consumer'
      fullPath: '/consumer'
      preLoaderRoute: typeof ConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inspections': {
      id: '/admin/inspections'
      path: '/inspections'
      fullPath: '/admin/inspections'
      preLoaderRoute: typeof AdminInspectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/consumer/': {
      id: '/consumer/'
      path: '/'
      fullPath: '/consumer/'
      preLoaderRoute: typeof ConsumerIndexRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/consumer/account': {
      id: '/consumer/account'
      path: '/account'
      fullPath: '/consumer/account'
      preLoaderRoute: typeof ConsumerAccountRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/consumer/checks': {
      id: '/consumer/checks'
      path: '/checks'
      fullPath: '/consumer/checks'
      preLoaderRoute: typeof ConsumerChecksRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/consumer/complaints': {
      id: '/consumer/complaints'
      path: '/complaints'
      fullPath: '/consumer/complaints'
      preLoaderRoute: typeof ConsumerComplaintsRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/consumer/rights': {
      id: '/consumer/rights'
      path: '/rights'
      fullPath: '/consumer/rights'
      preLoaderRoute: typeof ConsumerRightsRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/inspector/': {
      id: '/inspector/'
      path: '/'
      fullPath: '/inspector/'
      preLoaderRoute: typeof InspectorIndexRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/inspections': {
      id: '/inspector/inspections'
      path: '/inspections'
      fullPath: '/inspector/inspections'
      preLoaderRoute: typeof InspectorInspectionsRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/profile': {
      id: '/inspector/profile'
      path: '/profile'
      fullPath: '/inspector/profile'
      preLoaderRoute: typeof InspectorProfileRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/reports': {
      id: '/inspector/reports'
      path: '/reports'
      fullPath: '/inspector/reports'
      preLoaderRoute: typeof InspectorReportsRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/scan': {
      id: '/inspector/scan'
      path: '/scan'
      fullPath: '/inspector/scan'
      preLoaderRoute: typeof InspectorScanRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/reports': {
      id: '/officer/reports'
      path: '/reports'
      fullPath: '/officer/reports'
      preLoaderRoute: typeof OfficerReportsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/review': {
      id: '/officer/review'
      path: '/review'
      fullPath: '/officer/review'
      preLoaderRoute: typeof OfficerReviewRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/sellers': {
      id: '/officer/sellers'
      path: '/sellers'
      fullPath: '/officer/sellers'
      preLoaderRoute: typeof OfficerSellersRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/staff': {
      id: '/admin/users/staff'
      path: '/staff'
      fullPath: '/admin/users/staff'
      preLoaderRoute: typeof AdminUsersStaffRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/consumer/check/$id': {
      id: '/consumer/check/$id'
      path: '/check/$id'
      fullPath: '/consumer/check/$id'
      preLoaderRoute: typeof ConsumerCheckIdRouteImport
      parentRoute: typeof ConsumerRoute
    }
    '/inspector/inspections/': {
      id: '/inspector/inspections/'
      path: '/'
      fullPath: '/inspector/inspections/'
      preLoaderRoute: typeof InspectorInspectionsIndexRouteImport
      parentRoute: typeof InspectorInspectionsRoute
    }
    '/inspector/inspections/$id': {
      id: '/inspector/inspections/$id'
      path: '/$id'
      fullPath: '/inspector/inspections/$id'
      preLoaderRoute: typeof InspectorInspectionsIdRouteImport
      parentRoute: typeof InspectorInspectionsRoute
    }
    '/inspector/reports/': {
      id: '/inspector/reports/'
      path: '/'
      fullPath: '/inspector/reports/'
      preLoaderRoute: typeof InspectorReportsIndexRouteImport
      parentRoute: typeof InspectorReportsRoute
    }
    '/inspector/reports/$id': {
      id: '/inspector/reports/$id'
      path: '/$id'
      fullPath: '/inspector/reports/$id'
      preLoaderRoute: typeof InspectorReportsIdRouteImport
      parentRoute: typeof InspectorReportsRoute
    }
    '/officer/cases/$id': {
      id: '/officer/cases/$id'
      path: '/cases/$id'
      fullPath: '/officer/cases/$id'
      preLoaderRoute: typeof OfficerCasesIdRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/admin/users/customers/': {
      id: '/admin/users/customers/'
      path: '/customers'
      fullPath: '/admin/users/customers/'
      preLoaderRoute: typeof AdminUsersCustomersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/customers/$id': {
      id: '/admin/users/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/users/customers/$id'
      preLoaderRoute: typeof AdminUsersCustomersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersStaffRoute: typeof AdminUsersStaffRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminUsersCustomersIdRoute: typeof AdminUsersCustomersIdRoute
  AdminUsersCustomersIndexRoute: typeof AdminUsersCustomersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersStaffRoute: AdminUsersStaffRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminUsersCustomersIdRoute: AdminUsersCustomersIdRoute,
  AdminUsersCustomersIndexRoute: AdminUsersCustomersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminInspectionsRoute: typeof AdminInspectionsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRulesRoute: typeof AdminRulesRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminInspectionsRoute: AdminInspectionsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRulesRoute: AdminRulesRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ConsumerRouteChildren {
  ConsumerAccountRoute: typeof ConsumerAccountRoute
  ConsumerChecksRoute: typeof ConsumerChecksRoute
  ConsumerComplaintsRoute: typeof ConsumerComplaintsRoute
  ConsumerRightsRoute: typeof ConsumerRightsRoute
  ConsumerIndexRoute: typeof ConsumerIndexRoute
  ConsumerCheckIdRoute: typeof ConsumerCheckIdRoute
}

const ConsumerRouteChildren: ConsumerRouteChildren = {
  ConsumerAccountRoute: ConsumerAccountRoute,
  ConsumerChecksRoute: ConsumerChecksRoute,
  ConsumerComplaintsRoute: ConsumerComplaintsRoute,
  ConsumerRightsRoute: ConsumerRightsRoute,
  ConsumerIndexRoute: ConsumerIndexRoute,
  ConsumerCheckIdRoute: ConsumerCheckIdRoute,
}

const ConsumerRouteWithChildren = ConsumerRoute._addFileChildren(
  ConsumerRouteChildren,
)

interface InspectorInspectionsRouteChildren {
  InspectorInspectionsIdRoute: typeof InspectorInspectionsIdRoute
  InspectorInspectionsIndexRoute: typeof InspectorInspectionsIndexRoute
}

const InspectorInspectionsRouteChildren: InspectorInspectionsRouteChildren = {
  InspectorInspectionsIdRoute: InspectorInspectionsIdRoute,
  InspectorInspectionsIndexRoute: InspectorInspectionsIndexRoute,
}

const InspectorInspectionsRouteWithChildren =
  InspectorInspectionsRoute._addFileChildren(InspectorInspectionsRouteChildren)

interface InspectorReportsRouteChildren {
  InspectorReportsIdRoute: typeof InspectorReportsIdRoute
  InspectorReportsIndexRoute: typeof InspectorReportsIndexRoute
}

const InspectorReportsRouteChildren: InspectorReportsRouteChildren = {
  InspectorReportsIdRoute: InspectorReportsIdRoute,
  InspectorReportsIndexRoute: InspectorReportsIndexRoute,
}

const InspectorReportsRouteWithChildren =
  InspectorReportsRoute._addFileChildren(InspectorReportsRouteChildren)

interface InspectorRouteChildren {
  InspectorInspectionsRoute: typeof InspectorInspectionsRouteWithChildren
  InspectorProfileRoute: typeof InspectorProfileRoute
  InspectorReportsRoute: typeof InspectorReportsRouteWithChildren
  InspectorScanRoute: typeof InspectorScanRoute
  InspectorIndexRoute: typeof InspectorIndexRoute
}

const InspectorRouteChildren: InspectorRouteChildren = {
  InspectorInspectionsRoute: InspectorInspectionsRouteWithChildren,
  InspectorProfileRoute: InspectorProfileRoute,
  InspectorReportsRoute: InspectorReportsRouteWithChildren,
  InspectorScanRoute: InspectorScanRoute,
  InspectorIndexRoute: InspectorIndexRoute,
}

const InspectorRouteWithChildren = InspectorRoute._addFileChildren(
  InspectorRouteChildren,
)

interface OfficerRouteChildren {
  OfficerReportsRoute: typeof OfficerReportsRoute
  OfficerReviewRoute: typeof OfficerReviewRoute
  OfficerSellersRoute: typeof OfficerSellersRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  OfficerCasesIdRoute: typeof OfficerCasesIdRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerReportsRoute: OfficerReportsRoute,
  OfficerReviewRoute: OfficerReviewRoute,
  OfficerSellersRoute: OfficerSellersRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  OfficerCasesIdRoute: OfficerCasesIdRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConsumerRoute: ConsumerRouteWithChildren,
  InspectorRoute: InspectorRouteWithChildren,
  OfficerRoute: OfficerRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
