/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as InspectorIndexRouteImport } from './routes/inspector.index'
import { Route as InspectorInspectionsRouteImport } from './routes/inspector.inspections'
import { Route as InspectorScanRouteImport } from './routes/inspector.scan'
import { Route as InspectorInspectionsIndexRouteImport } from './routes/inspector.inspections.index'
import { Route as InspectorInspectionsIdRouteImport } from './routes/inspector.inspections.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorIndexRoute = InspectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorInspectionsRoute = InspectorInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorScanRoute = InspectorScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorInspectionsIndexRoute =
  InspectorInspectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InspectorInspectionsRoute,
  } as any)
const InspectorInspectionsIdRoute = InspectorInspectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InspectorInspectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inspector': typeof InspectorRouteWithChildren
  '/inspector/inspections': typeof InspectorInspectionsRouteWithChildren
  '/inspector/scan': typeof InspectorScanRoute
  '/inspector/': typeof InspectorIndexRoute
  '/inspector/inspections/$id': typeof InspectorInspectionsIdRoute
  '/inspector/inspections/': typeof InspectorInspectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inspector/scan': typeof InspectorScanRoute
  '/inspector': typeof InspectorIndexRoute
  '/inspector/inspections/$id': typeof InspectorInspectionsIdRoute
  '/inspector/inspections': typeof InspectorInspectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inspector': typeof InspectorRouteWithChildren
  '/inspector/inspections': typeof InspectorInspectionsRouteWithChildren
  '/inspector/scan': typeof InspectorScanRoute
  '/inspector/': typeof InspectorIndexRoute
  '/inspector/inspections/$id': typeof InspectorInspectionsIdRoute
  '/inspector/inspections/': typeof InspectorInspectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inspector'
    | '/inspector/inspections'
    | '/inspector/scan'
    | '/inspector/'
    | '/inspector/inspections/$id'
    | '/inspector/inspections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inspector/scan'
    | '/inspector'
    | '/inspector/inspections/$id'
    | '/inspector/inspections'
  id:
    | '__root__'
    | '/'
    | '/inspector'
    | '/inspector/inspections'
    | '/inspector/scan'
    | '/inspector/'
    | '/inspector/inspections/$id'
    | '/inspector/inspections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InspectorRoute: typeof InspectorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector/': {
      id: '/inspector/'
      path: '/'
      fullPath: '/inspector/'
      preLoaderRoute: typeof InspectorIndexRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/inspections': {
      id: '/inspector/inspections'
      path: '/inspections'
      fullPath: '/inspector/inspections'
      preLoaderRoute: typeof InspectorInspectionsRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/scan': {
      id: '/inspector/scan'
      path: '/scan'
      fullPath: '/inspector/scan'
      preLoaderRoute: typeof InspectorScanRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/inspections/': {
      id: '/inspector/inspections/'
      path: '/'
      fullPath: '/inspector/inspections/'
      preLoaderRoute: typeof InspectorInspectionsIndexRouteImport
      parentRoute: typeof InspectorInspectionsRoute
    }
    '/inspector/inspections/$id': {
      id: '/inspector/inspections/$id'
      path: '/$id'
      fullPath: '/inspector/inspections/$id'
      preLoaderRoute: typeof InspectorInspectionsIdRouteImport
      parentRoute: typeof InspectorInspectionsRoute
    }
  }
}

interface InspectorInspectionsRouteChildren {
  InspectorInspectionsIdRoute: typeof InspectorInspectionsIdRoute
  InspectorInspectionsIndexRoute: typeof InspectorInspectionsIndexRoute
}

const InspectorInspectionsRouteChildren: InspectorInspectionsRouteChildren = {
  InspectorInspectionsIdRoute: InspectorInspectionsIdRoute,
  InspectorInspectionsIndexRoute: InspectorInspectionsIndexRoute,
}

const InspectorInspectionsRouteWithChildren =
  InspectorInspectionsRoute._addFileChildren(InspectorInspectionsRouteChildren)

interface InspectorRouteChildren {
  InspectorInspectionsRoute: typeof InspectorInspectionsRouteWithChildren
  InspectorScanRoute: typeof InspectorScanRoute
  InspectorIndexRoute: typeof InspectorIndexRoute
}

const InspectorRouteChildren: InspectorRouteChildren = {
  InspectorInspectionsRoute: InspectorInspectionsRouteWithChildren,
  InspectorScanRoute: InspectorScanRoute,
  InspectorIndexRoute: InspectorIndexRoute,
}

const InspectorRouteWithChildren = InspectorRoute._addFileChildren(
  InspectorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InspectorRoute: InspectorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
